"""Shared workflow status constants for the extrusion pilot."""

STATUS_IMPORTED = "imported"
STATUS_PENDING = "pending"
STATUS_RUNNING = "running"
STATUS_PAUSED = "paused"
STATUS_COMPLETED = "completed"
STATUS_CANCELLED = "cancelled"

CARD_STATUSES = (
    STATUS_IMPORTED,
    STATUS_PENDING,
    STATUS_RUNNING,
    STATUS_PAUSED,
    STATUS_COMPLETED,
    STATUS_CANCELLED,
)

ACTIVE_TERMINAL_STATUSES = (
    STATUS_PENDING,
    STATUS_RUNNING,
    STATUS_PAUSED,
)

ARCHIVE_STATUSES = (
    STATUS_COMPLETED,
    STATUS_CANCELLED,
)
